#!/usr/bin/perl
use strict;
use GPS::gpsd;
my ($host,$port)=split(q{:}, shift());
$host||=q{localhost};
$port||=q{2947};

my $gps=GPS::gpsd->new(host=>$host, port=>$port) || die("Error: Cannot connect to the gpsd server");

print "GPS::gpsd Version:\t", $gps->VERSION, "\n";
print "gpsd Version:\t\t", $gps->daemon, "\n";
print "gpsd Commands:\t\t", $gps->commands, "\n";
print "Host:\t\t\t", $gps->host, "\n";
print "Port:\t\t\t", $gps->port, "\n";
