#!/usr/bin/perl
use strict;
use lib './perl-GPS-gpsd-0.3';
use GPS::gpsd;

my $gps=GPS::gpsd->new(host=>'192.168.33.130');
my $point=$gps->get();
print "gpsd.pm Version:", $gps->VERSION, "\n";
print "gpsd Version:", $gps->server, "\n";
print "gpsd Commands:", $gps->commands, "\n";
print "Status:", $point->status, "\n";
print "Lat:", $point->lat, " Lon:", $point->lon, "\n";
print "Host:", $gps->host, " Port:", $gps->port, "\n";

$gps->register(sub=>\&gpsd_handler);

sub gpsd_handler {
  my $p=shift();
  print join " ", "Fix", $p->status, $p->lat, $p->lon, "\n";
}
