--- #YAML:1.0
name:                GPS-gpsd
version:             0.5
abstract:            A module that provides a perl interface to the gpsd daemon.
license:             perl
generated_by:        Hand (Any help here?)
author:              Michael R. Davis <perl michaelrdavis.com>
distribution_type:   module
requires:     
    IO::Socket;                    0
    Math::Trig;                    0
